### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by epistularum** [wareya/nazeka_epwing_converter#3]
Is it possible to have an explanation on how to use the tool? I'd like to provide feedback.

**Comment by wareya** [comment]
Are you familiar with using software that has a command-line interface?

**Comment by epistularum** [comment]
Yes I am.

**Comment by wareya** [comment]
First thing you need to do is convert an epwing dictionary to json with https://github.com/FooSoft/zero-epwing - this looks something like

    ./zero-epwing.exe --entries --pretty shinmeikai/ > my_zeroepwing_shinmeikai_rip.json

Then you use nazeka_epwing_converter on that zeroepwing rip like so:

    ./nazeka_epwing_converter.exe my_zeroepwing_shinmeikai_rip.json > my_nazeka_json_dictionary_shinmeikai.json

Note: I'm running from a unix-like shell (git bash) in a weird locale, so it might not work for you. I think that cmd.exe doesn't support pipes the same way unix shells do? Maybe powershell would work? I don't know.

[nazeka_epwing_converter.zip](https://github.com/wareya/nazeka_epwing_converter/files/3203997/nazeka_epwing_converter.zip)

It would be even better if you somehow manage to install rust (via rustup, or https://rustup.rs/ ) and compile nazeka_epwing_converter yourself (through "cargo", the toolchain frontend for normal rust projects), because then you could poke around the code and try making changes to filtering regexes or logic, though be warned that rust is a ***very*** unforgiving language so if you can't program there might not be a lot you can actually do.

**Comment by epistularum** [comment]
I'm also on GNU/Linux.
I have generated the zeroepwing rip without any issue but using the provided exe and running the next command through wine

````
./nazeka_epwing_converter.exe my_zeroepwing_shinmeikai_rip.json > my_nazeka_json_dictionary_shinmeikai.json
````
outputs this error
````
002b:fixme:thread:SetThreadStackGuarantee (0x23fd30): stub
WARNING: zero-epwing rips this dictionary incorrectly.
Three entries are missing their definitions, which will cause this converter to crash.
You need to add the correct definitions manually. Instructions follow.

WARNING: The definitions should not contain literal linebreaks. Remove any that are created by copying the text out of your terminal, and do not convert the \n escape sequnces to real newlines.

from:
"heading": "かもく【科目】クワモク[0]"
to:
"heading": "かもく【科目】クワモク[0]",
"text": "(一)幾つかの種類に分けた、一つひとつの項目。\n 「勘定―[5]」\n(二)種類分けした教科の一つひとつ。\n 「高等学校の国語科には国語・国語・古典・現代文・国語表現などの―がある／必修―[5]」\n[表記](二)は、「課目」とも書く。"

from:
"heading": "こうぶん【高文】カウブン[0]"
to:
"heading": "こうぶん【高文】カウブン[0]",
"text": "もと、「高等文官試験」の略。現在の「国家公務員採用試験種」に当たる。"

from:
"heading": "キャリア[1]"
to:
"heading": "キャリア[1]",
"text": "[一]〔career＝経歴〕\n(一)その方面で実際に場数を踏んで来た経験年数。〔狭義では、競技歴・試合経験を指す〕\n 「―ウーマン」\n(二)国家公務員試験種に合格した者の通称。\n 「―組グミ・ノン―」\n[二]〔carrier〕\n(一)自転車などの荷台。\n(二)品物を運ぶ器具。\n 「―カー」\n(三)航空会社・運輸会社。\n 「フラッグ―」\n(四)病原菌やウイルスに感染しながら発病せず、しかも保菌し続ける人。保菌者。"

Note: The exact presence of a , on the first line and lack of a , on the second line are mandatory.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `text`", line: 43003, column: 17)', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
````
So I suppose compiling it myself is a better idea that running it through wine?

edit: Well maybe next time I should actually read the error message.

**Comment by wareya** [comment]
No, that error is expected. Zero-Epwing actually outputs inconsistent JSON for this dictionary, and that warning contains instructions on how to fix it. Until the .json file is manually fixed, the JSON library that nazeka_epwing_converter uses throws a hard crash, It sucks. I should probably replace the JSON library I'm using with one that won't crash, but they all kind of suck...

**Comment by epistularum** [comment]
Yeah sorry I read quickly the error message without paying attention.

**Comment by epistularum** [comment]
I ran it again after editing and it worked like a charm.

**Comment by wareya** [comment]
Nice.

**Comment by epistularum** [comment]
Maybe consider adding this to the readme?

**Comment by wareya** [comment]
Sure.
